blueprint:
  name: iPhone HVAC Filter Change Reminder
  description: Sends a reminder to specified iPhones about the HVAC filter change at set intervals. Ensure your HVAC system stays efficient by routinely replacing or cleaning the filter.
  domain: automation
  input:
    iphone_targets:
      name: iPhone Targets
      description: The iPhones to notify.
      selector:
        entity:
          domain: notify
          device_class: mobile_app
          multiple: true
    days_interval:
      name: Days Interval
      description: Notify every X days.
      default: 60
      selector:
        number:
          min: 1
          max: 365
          unit_of_measurement: "days"

trigger:
  platform: time_pattern
  days: !input "days_interval"

action:
  - service: notify.notify
    data:
      message: "It's time to change your HVAC's filter!"
      target: !input "iphone_targets"
