blueprint:
  name: HVAC Filter Change Reminder
  description: Send a notification to change the HVAC filter every 90 days starting from January 1st.
  domain: automation
  input:
    notify_device_1:
      name: First Notification Device
      description: The first device to receive the reminder.
      selector:
        entity:
          domain: notify
    notify_device_2:
      name: Second Notification Device
      description: The second device to receive the reminder (optional).
      selector:
        entity:
          domain: notify
          default: null

trigger:
  platform: time_pattern
  days: "1"

condition:
  condition: template
  value_template: "{{ now().strftime('%j')|int % 90 == 1 }}"

action:
  - service: "notify.{{ notify_device_1 }}"
    data:
      title: "HVAC Filter Reminder"
      message: "It's time to change the HVAC filter!"
  - condition: template
    value_template: "{{ notify_device_2 != null }}"
  - service: "notify.{{ notify_device_2 }}"
    data:
      title: "HVAC Filter Reminder"
      message: "It's time to change the HVAC filter!"
